POST http://localhost:3001/api/login
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc3BlcmxpIiwiaWQiOiI1YTcxZWM0Zjk1ZGViNjE5YjQyYmFlOWQiLCJpYXQiOjE1MTc0MTk5MTN9.Hqa9gZoQAI-vSfCiDz2Yek6F5xqNrVWBEBZRPMtZuSk
{
  "username": "jasperli",
  "password": "m134214test"
}